import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Dancing_Script } from "next/font/google";
import { Container, SSRProvider } from "../components/bootstrap";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });
const dancingScript = Dancing_Script({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "NextJS 13.4 Image Gallery",
    description: "Generated by create next app",
};
//npx create-next-app@latest
//npm i bootstrap react-bootstrap
//npm run dev
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SSRProvider>
                    <NavBar />
                    <main>
                        <Container className="my-4">{children}</Container>
                    </main>
                </SSRProvider>
            </body>
        </html>
    );
}
